### ISSUE TITLE
Hyphens lost

### ISSUE THREAD

**Issue by o90o** [VikParuchuri/pdftext#1]
Firstly thanks for publishing this tool! It's already better than pdf2text from poppler, which is awesome!

There is a problem with lost hyphenations in certain documents.

Please see this PDF file:

[taxation.pdf](https://github.com/VikParuchuri/pdftext/files/15144019/taxation.pdf)

On page 2 there are two lines:

```
 The deduction of special professional expenses under paragraphs 1 and 2 is permit-
ted ...
```

Notice the hyphenation of the word `permitted`.

The output of pdftext is missing the hyphen:

```
3 The deduction of special professional expenses under paragraphs 1 and 2 is permit
ted 
```

How could this be fixed? I checked the source code but there is nothing obviously removing hyphers.

**Comment by VikParuchuri** [comment]
I just fixed this in master, will make a new release soon.  With json output, it will always keep hyphens.  With plain text output, it will remove hyphens and wrap words unless you pass the `keep_hyphens` flag
