### ISSUE TITLE
Unable to install latest versions

### ISSUE THREAD

**Issue by Mahendranath94** [VikParuchuri/pdftext#20]
Collecting pdftext==0.3.18
  Using cached pdftext-0.3.18-py3-none-any.whl.metadata (8.2 kB)
INFO: pip is looking at multiple versions of pdftext to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime<2.0.0,>=1.19.2 (from pdftext) (from versions: none)
ERROR: No matching distribution found for onnxruntime<2.0.0,>=1.19.2

**Comment by VikParuchuri** [comment]
This should be fixed, we no longer use onnxruntime
