### ISSUE TITLE
Sklearn raises `InconsistentVersionWarning`

### ISSUE THREAD

**Issue by lsorber** [VikParuchuri/pdftext#5]
It seems that the version of sci-kit learn that was used to train [dt.joblib](https://github.com/VikParuchuri/pdftext/blob/master/models/dt.joblib) (v1.4.2) may not be compatible with the version of sci-kit learn [as specified by pyproject.toml](https://github.com/VikParuchuri/pdftext/blob/master/pyproject.toml#L21) (>=v1.4.2), and that can result in the following warning when parsing a PDF:

```
`InconsistentVersionWarning`: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```

**Comment by VikParuchuri** [comment]
This has been fixed in the new version - we're using onnx instead

**Comment by lsorber** [comment]
Great, thanks!
